version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: .
    image: simulator
    ports:
      - '9999:9999'

